spring:
  profiles:
      active: dev

server:
  port: 8600

logging:
  config: classpath:config/logback-spring.xml
log_filename: LogCollector_Log


---
spring:
  profiles: dev

log_level: INFO
log_path: /Users/gavinguan/Desktop/youCanDeleteMe

ymlConfig:
  context: develop
  hawkeyeRepositoryPath: /Users/gavinguan/Desktop/youCanDeleteMe/hawkeye

---
spring:
  profiles: prod

log_level: INFO
log_path: youCanDeleteMe

ymlConfig:
  context: product
  hawkeyeRepositoryPath: /Users/gavinguan/Desktop/youCanDeleteMe/hawkeye



